### PR TITLE
404 page

### PR DESCRIPTION
**Pull request by edumoreira1506**
Here I am! I don't know if you like of this styles of page with a little piece of fun, in person I like so much. 
Peek 2019-10-15 14-38

### CODE REVIEW

**Comment by edumoreira1506** [comment]
Oh, before my commit I did pull in master. Did i break anything or it's ok? I saw some commits than don't belongs to this pr.

**Comment by everek** [comment]
Hey @edumoreira1506 , sorry I did some refactoring. Can you pull develop again and resolve the conflicts?
The 404 page looks nice 😃

**Comment by edumoreira1506** [comment]
Nice!

**Comment by everek** [comment]
Awesome, thanks for your contribution!

**Pull request merged**
